2025-03-24 13:56:07,933 INFO    MainThread:753529 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-24 13:56:07,933 INFO    MainThread:753529 [wandb_setup.py:_flush():67] Configure stats pid to 753529
2025-03-24 13:56:07,933 INFO    MainThread:753529 [wandb_setup.py:_flush():67] Loading settings from /home/daniel/.config/wandb/settings
2025-03-24 13:56:07,933 INFO    MainThread:753529 [wandb_setup.py:_flush():67] Loading settings from /home/daniel/workspace/actuator_modeling/wandb/settings
2025-03-24 13:56:07,934 INFO    MainThread:753529 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-24 13:56:07,934 INFO    MainThread:753529 [wandb_init.py:setup_run_log_directory():647] Logging user logs to ./wandb/run-20250324_135607-rys79ybg/logs/debug.log
2025-03-24 13:56:07,934 INFO    MainThread:753529 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to ./wandb/run-20250324_135607-rys79ybg/logs/debug-internal.log
2025-03-24 13:56:07,934 INFO    MainThread:753529 [wandb_init.py:init():761] calling init triggers
2025-03-24 13:56:07,934 INFO    MainThread:753529 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'model': '../model/mlp.yaml', 'data': '../data/actuator_data.yaml', 'batch_size': 64, 'learning_rate': 0.001, 'weight_decay': 1e-05, 'max_epochs': 100, 'patience': 10, 'num_workers': 4, 'log_frequency': 50, 'val_check_interval': 1.0, 'viz_frequency': 5, 'wandb': {'project_name': 'actuator-modeling', 'entity': 'your_wandb_entity'}, '_wandb': {}}
2025-03-24 13:56:07,934 INFO    MainThread:753529 [wandb_init.py:init():784] starting backend
2025-03-24 13:56:07,934 INFO    MainThread:753529 [wandb_init.py:init():788] sending inform_init request
2025-03-24 13:56:07,940 INFO    MainThread:753529 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-24 13:56:07,940 INFO    MainThread:753529 [wandb_init.py:init():798] backend started and connected
2025-03-24 13:56:07,942 INFO    MainThread:753529 [wandb_init.py:init():891] updated telemetry
2025-03-24 13:56:07,943 INFO    MainThread:753529 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-24 13:56:08,439 ERROR   MainThread:753529 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/daniel/miniconda3/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 963, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404: {"data":{"upsertBucket":null},"errors":[{"message":"entity your_wandb_entity not found during upsertBucket","path":["upsertBucket"]}]}
2025-03-24 13:56:09,440 INFO    MsgRouterThr:753529 [mailbox.py:close():129] Closing mailbox, abandoning 0 handles.
